#!/bin/bash
#this program tests if install.sh works
bash ../install.sh

#checking for presence of car rental app
if [ -f "~/Desktop/CarRentalApp" ]; then
	echo "Test one: CarRentalApp present, success"
else
	echo "Test two: CarRentalApp not present, failure"
fi
 
 
