#!/bin/bash

#This file tests the first success criterion, namely,
#A car can be createde and stored in the database

#Step 1: create a car using the script create
bash ../createcar.sh TXM301 nissan red 9

#step 2: check that the license file .txt was created
if [ -f "../car/TXM301.txt" ]; then
	echo "Test one: a txt file was created inside the database: passedD"
else
	echo "Test one: Error. File not found: not passed"
fi
 
#step 3 : Check that the car waas adaded to main file

lastline=$( tail -n 1 ../car/maincarfile.txt )

if [ "TXM301 nissan red 9" == "$lastline" ]; then
	echo "Test two: record wasa entered correctly: passed"
else
	echo "Test two: Failed"
fi
